name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  build:
    if: true     
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.9"] 
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Create Virtual Env
        run: |
              py -${{ matrix.python-version }} -m venv env
              env/Scripts/activate

      - name: Install Dependencies
        run: |
              env/Scripts/activate
              pip install --upgrade pip
              pip install -r requirements.txt

      - name: Run Simple File
        run: |
              env/Scripts/activate
              python test.py
            
      - name: Delete env
        run:  rm -r env